builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/sumocli
    ldflags:
      - -X 'github.com/dpc-sdp/sumocli/internal/build.Build={{.Commit}}'
      - -X 'github.com/dpc-sdp/sumocli/internal/build.Date={{.Date}}'
      - -X 'github.com/dpc-sdp/sumocli/internal/build.Version={{.Version}}'
    ignore:
      - goos: windows
        goarch: arm64
dockers:
  - image_templates:
      - "ghcr.io/dpc-sdp/sumocli:{{.Version}}-amd64"
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/dpc-sdp/sumocli
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
    skip_push: false
    use: podman
  - image_templates:
      - "ghcr.io/dpc-sdp/sumocli:{{.Version}}-arm64"
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/dpc-sdp/sumocli
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
    skip_push: false
    use: podman
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip
release:
  disable: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
